-- RIHULA ADMIN ACTIVITY / AUDIT LOG
-- Run this AFTER the RIHULA admin security SQL.
--
-- This records which authenticated admin performed a change. It is designed
-- for multiple admins: every entry stores the admin auth UUID, name and email
-- as a snapshot, so old records remain attributable even if an admin later
-- changes their profile name/email.

BEGIN;

CREATE TABLE IF NOT EXISTS public.activity_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_auth_id uuid NOT NULL,
  admin_name text NOT NULL DEFAULT 'Admin',
  admin_email text,
  action text NOT NULL,
  entity_type text,
  entity_id text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS activity_logs_created_at_idx
  ON public.activity_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS activity_logs_admin_auth_id_idx
  ON public.activity_logs (admin_auth_id);

DROP POLICY IF EXISTS "Admins read activity logs" ON public.activity_logs;
CREATE POLICY "Admins read activity logs"
ON public.activity_logs
FOR SELECT TO authenticated
USING (public.is_rihula_admin());

-- No direct INSERT/UPDATE/DELETE policy is intentionally granted to admins.
-- Inserts happen through the protected functions below, preventing a browser
-- from pretending that another admin performed an action.

CREATE OR REPLACE FUNCTION public.log_admin_activity(p_action text)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_name text;
  v_email text;
  v_id bigint;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'You must be signed in as an admin.';
  END IF;

  SELECT m.name, m.email
    INTO v_name, v_email
  FROM public.members m
  WHERE m.auth_id = v_user_id
    AND m.is_admin = true
    AND lower(coalesce(m.status, 'active')) NOT IN ('blocked','suspended','inactive')
  LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Only an active RIHULA admin can create activity records.';
  END IF;

  INSERT INTO public.activity_logs (
    admin_auth_id, admin_name, admin_email, action
  )
  VALUES (
    v_user_id,
    coalesce(nullif(trim(v_name), ''), 'Admin'),
    nullif(trim(v_email), ''),
    left(coalesce(nullif(trim(p_action), ''), 'Admin activity'), 500)
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.log_admin_activity(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.log_admin_activity(text) TO authenticated;

-- Automatically audit admin database mutations. This means the activity
-- panel still records actions even when the change comes from another admin
-- page or from a future feature that writes to one of these core tables.
CREATE OR REPLACE FUNCTION public.rihula_audit_admin_mutation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_name text;
  v_email text;
  v_action text;
  v_entity_id text;
  v_is_admin boolean := false;
  v_phone text;
  v_member_name text;
  v_amount text;
  v_title text;
  v_goal text;
BEGIN
  IF v_user_id IS NULL THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  SELECT m.name, m.email, true
    INTO v_name, v_email, v_is_admin
  FROM public.members m
  WHERE m.auth_id = v_user_id
    AND m.is_admin = true
    AND lower(coalesce(m.status, 'active')) NOT IN ('blocked','suspended','inactive')
  LIMIT 1;

  IF NOT v_is_admin THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  IF TG_OP = 'INSERT' THEN
    v_entity_id := COALESCE(to_jsonb(NEW)->>'id', to_jsonb(NEW)->>'phone', '');
  ELSE
    v_entity_id := COALESCE(to_jsonb(NEW)->>'id', to_jsonb(OLD)->>'id', to_jsonb(NEW)->>'phone', to_jsonb(OLD)->>'phone', '');
  END IF;

  IF TG_TABLE_NAME = 'members' THEN
    v_phone := COALESCE(to_jsonb(NEW)->>'phone', to_jsonb(OLD)->>'phone', '');
    v_member_name := COALESCE(to_jsonb(NEW)->>'name', to_jsonb(OLD)->>'name', 'member');
    v_action := CASE TG_OP
      WHEN 'INSERT' THEN 'Added member: ' || v_member_name || ' (' || v_phone || ')'
      WHEN 'UPDATE' THEN 'Updated member: ' || v_member_name || ' (' || v_phone || ')'
      WHEN 'DELETE' THEN 'Deleted member: ' || v_member_name || ' (' || v_phone || ')'
    END;
  ELSIF TG_TABLE_NAME = 'contributions' THEN
    v_phone := COALESCE(to_jsonb(NEW)->>'member_phone', to_jsonb(OLD)->>'member_phone', '');
    v_amount := COALESCE(to_jsonb(NEW)->>'amount', to_jsonb(OLD)->>'amount', '0');
    v_action := CASE TG_OP
      WHEN 'INSERT' THEN 'Recorded contribution: KSh ' || v_amount || ' for ' || v_phone
      WHEN 'UPDATE' THEN 'Edited contribution: KSh ' || v_amount || ' for ' || v_phone
      WHEN 'DELETE' THEN 'Deleted contribution: KSh ' || v_amount || ' for ' || v_phone
    END;
  ELSIF TG_TABLE_NAME = 'withdrawals' THEN
    v_phone := COALESCE(to_jsonb(NEW)->>'member_phone', to_jsonb(OLD)->>'member_phone', '');
    v_amount := COALESCE(to_jsonb(NEW)->>'amount', to_jsonb(OLD)->>'amount', '0');
    v_action := CASE TG_OP
      WHEN 'INSERT' THEN 'Recorded withdrawal: KSh ' || v_amount || ' for ' || v_phone
      WHEN 'UPDATE' THEN 'Edited withdrawal: KSh ' || v_amount || ' for ' || v_phone
      WHEN 'DELETE' THEN 'Deleted withdrawal: KSh ' || v_amount || ' for ' || v_phone
    END;
  ELSIF TG_TABLE_NAME = 'announcements' THEN
    v_title := COALESCE(to_jsonb(NEW)->>'title', to_jsonb(OLD)->>'title', 'announcement');
    v_action := CASE TG_OP
      WHEN 'INSERT' THEN 'Posted announcement: ' || v_title
      WHEN 'UPDATE' THEN 'Edited announcement: ' || v_title
      WHEN 'DELETE' THEN 'Deleted announcement: ' || v_title
    END;
  ELSIF TG_TABLE_NAME = 'notifications' THEN
    v_title := COALESCE(to_jsonb(NEW)->>'title', to_jsonb(OLD)->>'title', 'notification');
    v_action := CASE TG_OP
      WHEN 'INSERT' THEN 'Sent notification: ' || v_title
      WHEN 'UPDATE' THEN 'Edited notification: ' || v_title
      WHEN 'DELETE' THEN 'Deleted notification: ' || v_title
    END;
  ELSIF TG_TABLE_NAME = 'settings' THEN
    v_goal := COALESCE(to_jsonb(NEW)->>'group_goal', to_jsonb(OLD)->>'group_goal', '0');
    v_action := CASE TG_OP
      WHEN 'INSERT' THEN 'Created settings record (group goal KSh ' || v_goal || ')'
      WHEN 'UPDATE' THEN 'Updated group goal/settings (KSh ' || v_goal || ')'
      WHEN 'DELETE' THEN 'Deleted settings record'
    END;
  ELSE
    v_action := TG_OP || ' on ' || TG_TABLE_NAME;
  END IF;

  INSERT INTO public.activity_logs (
    admin_auth_id, admin_name, admin_email, action, entity_type, entity_id
  )
  VALUES (
    v_user_id,
    coalesce(nullif(trim(v_name), ''), 'Admin'),
    nullif(trim(v_email), ''),
    left(coalesce(v_action, 'Admin activity'), 500),
    TG_TABLE_NAME,
    nullif(v_entity_id, '')
  );

  RETURN COALESCE(NEW, OLD);
END;
$$;

REVOKE ALL ON FUNCTION public.rihula_audit_admin_mutation() FROM PUBLIC;

-- Recreate triggers safely. If a table does not exist in this project,
-- comment out only that table's trigger block before running the SQL.
DROP TRIGGER IF EXISTS rihula_audit_members ON public.members;
CREATE TRIGGER rihula_audit_members
AFTER INSERT OR UPDATE OR DELETE ON public.members
FOR EACH ROW EXECUTE FUNCTION public.rihula_audit_admin_mutation();

DROP TRIGGER IF EXISTS rihula_audit_contributions ON public.contributions;
CREATE TRIGGER rihula_audit_contributions
AFTER INSERT OR UPDATE OR DELETE ON public.contributions
FOR EACH ROW EXECUTE FUNCTION public.rihula_audit_admin_mutation();

DROP TRIGGER IF EXISTS rihula_audit_withdrawals ON public.withdrawals;
CREATE TRIGGER rihula_audit_withdrawals
AFTER INSERT OR UPDATE OR DELETE ON public.withdrawals
FOR EACH ROW EXECUTE FUNCTION public.rihula_audit_admin_mutation();

DROP TRIGGER IF EXISTS rihula_audit_announcements ON public.announcements;
CREATE TRIGGER rihula_audit_announcements
AFTER INSERT OR UPDATE OR DELETE ON public.announcements
FOR EACH ROW EXECUTE FUNCTION public.rihula_audit_admin_mutation();

-- Notifications may not exist in every older RIHULA database. Create this
-- trigger only if public.notifications already exists.
DROP TRIGGER IF EXISTS rihula_audit_notifications ON public.notifications;
CREATE TRIGGER rihula_audit_notifications
AFTER INSERT OR UPDATE OR DELETE ON public.notifications
FOR EACH ROW EXECUTE FUNCTION public.rihula_audit_admin_mutation();

DROP TRIGGER IF EXISTS rihula_audit_settings ON public.settings;
CREATE TRIGGER rihula_audit_settings
AFTER INSERT OR UPDATE OR DELETE ON public.settings
FOR EACH ROW EXECUTE FUNCTION public.rihula_audit_admin_mutation();

COMMIT;
